version: '3.7'

networks:
  network-zabbix:
    driver: bridge

services:
  mysql:
    container_name: mysql-zabbix
    image: mysql:8.0
    networks:
      - network-zabbix
    restart: unless-stopped
    ports:
      - '3306:3306'
    volumes:
      - './zabbix/mysql:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=DevDeividMoura
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=DevDeividMoura
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8
      - --collation-server=utf8_bin

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql
    networks:
      - network-zabbix
    restart: unless-stopped
    ports:
      - '10051:10051'
    volumes:
      - './zabbix/alertscripts:/usr/lib/zabbix/alertscripts'
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=DevDeividMoura
      - MYSQL_ROOT_PASSWORD=DevDeividMoura
    depends_on:
      - mysql

  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-apache-mysql
    networks:
      - network-zabbix
    restart: unless-stopped
    ports:
      - '8888:8080'   
      # - '8445:8443'
    environment:
      - ZBX_SERVER_HOST="zabbix-server"
      - DB_SERVER_HOST=mysql
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=DevDeividMoura
      - MYSQL_ROOT_PASSWORD=DevDeividMoura
      - PHP_TZ=America/Sao_Paulo
    depends_on:
      - mysql
      - zabbix-server

  grafana:
    container_name: grafana
    image: grafana/grafana
    networks:
      - network-zabbix
    restart: always
    ports:
      - '3000:3000'
    environment: 
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    depends_on:
      - zabbix-server

  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent2
    networks:
      - network-zabbix
    restart: always
    privileged: true
    volumes:
      - /var/run:/var/run
    ports:
      - '10050:10050'
    environment:
      - ZBX_HOSTNAME=Zabbix server
      - ZBX_SERVER_HOST=zabbix-server
